@startuml
!theme plain
skinparam packageStyle folder
skinparam backgroundColor #ffffff

title Diagrama de Paquetes - Módulo Pasajes (Arquitectura Monolítica)

package "pe.com.transsync.pasajes" #f0f8ff {

    package "controller" #e6f2ff {
        class PasajesController
        note bottom: Expone las APIs\n(Endpoints REST)
    }

    package "service" #e6f2ff {
        interface IPasajeService
        class PasajeServiceImpl
        note bottom: Reglas de negocio\ny llamadas internas
    }

    package "repository" #e6f2ff {
        interface IPasajeRepository
        note bottom: Consultas a\nla Base de Datos Central
    }

    package "model" #e6f2ff {
        package "entity" {
            class Boleto
            class Ruta
        }
        package "dto" {
            class VentaRequestDTO
            class VentaResponseDTO
        }
    }
}

' Dependencias entre paquetes (Las flechas muestran quién llama a quién)
controller ..> service : " usa"
controller ..> dto : " recibe/envía"

service ..> repository : " usa"
service ..> entity : " procesa"
service ..> dto : " mapea"

repository ..> entity : " persiste"

@enduml