@startuml
left to right direction
skinparam packageStyle rectangle

actor "Usuario" as UsuarioNormal
actor "Usuario Vendedor\n(Sucursal/Central)" as Vendedor

rectangle "Sistema TRANS_SYNC" {
  usecase "Iniciar Sesión" as UC_Login
  usecase "Registrar Venta" as UC_Venta
  usecase "Visualizar Comprobante" as UC_Comprobante
}

UsuarioNormal --> UC_Login
Vendedor --> UC_Venta

' Relaciones de inclusión hola(Registrar venta requiere iniciar sesión y genera comprobante)
UC_Venta ..> UC_Login : <<include>>
UC_Venta ..> UC_Comprobante : <<include>>
@enduml