@startuml
autonumber
skinparam maxMessageSize 150
skinparam participant {
    BackgroundColor #e2e8f0
    BorderColor #475569
}

title Diagrama de Secuencia: Vender un Pasaje (Arquitectura Monolítica)

actor "Despachador\n(Counter)" as despachador
participant "App Web\n(Frontend)" as web
participant "Módulo Autenticación\n(Filtro Spring Security)" as mod_auth
participant "Módulo Pasajes\n(Service)" as mod_pasajes
participant "Módulo Liquidación\n(Auditoría Service)" as mod_auditoria

despachador -> web : Selecciona ruta, asiento,\ningresa DNI y confirma venta
activate web

web -> mod_auth : POST /api/ventas\n(Header: Token JWT)
activate mod_auth

note right of mod_auth: El filtro intercepta\nla petición por seguridad

mod_auth -> mod_auth : Validar Token JWT\n(Rol: Despachador)

mod_auth -> mod_pasajes : Invocación interna:\nvenderPasaje(datos)
activate mod_pasajes

mod_pasajes -> mod_pasajes : Validar disponibilidad\nde asientos (Máx 7)
mod_pasajes -> mod_pasajes : Persistir venta en BD Central

note right of mod_pasajes: Comunicación directa\nmediante llamadas a métodos locales

mod_pasajes -> mod_auditoria : Invocación: registrarIngresoCaja(monto, despachador)
activate mod_auditoria
mod_auditoria -> mod_auditoria : Guardar log en BD Central
mod_auditoria --> mod_pasajes : Retorno de ejecución (void/OK)
deactivate mod_auditoria

mod_pasajes --> mod_auth : Objeto Boleto generado
deactivate mod_pasajes

mod_auth --> web : 201 Created (Datos del boleto JSON)
deactivate mod_auth

web --> despachador : Muestra Comprobante\n(Listo para imprimir)
deactivate web

@enduml