@startuml
|#LightBlue|Escenario Funcional (Usuario)|
start
:Inicia Sesión;
:Accede al módulo ventas;
:Busca/Selecciona cliente;
:Selecciona productos;
:Ingresa cantidad;
:Confirma venta;

|#LightPink|Caso Técnico (Sistema - TRANS_SYNC Monolito)|
:Filtro de Seguridad\n(Módulo Autenticación);
note right: Consulta BD Central\n(Esquema Auth)
:Ventas Service\n(Módulo Pasajes / Ventas);
note right: Lógica interna en memoria\nsin saltos de red
:Validar Stock / Asientos;
:Inventario Service\n(Módulo Gestión Rutas);
note right: Consulta/Actualiza\nBD Central
:Respuesta al Frontend\n(Venta Registrada JSON);

|#LightBlue|Escenario Funcional (Usuario)|
:Visualizar comprobante;
stop
@enduml