@startuml
!theme plain
left to right direction
skinparam rectangle {
    BackgroundColor #e6f2ff
    BorderColor #0b4884
}

title Diagrama de Comunicación: Rastrear Encomienda (Arquitectura Monolítica)

rectangle "Pasajero (Cliente)" as cliente
rectangle ": App Web (Frontend)" as app
rectangle ": Módulo Encomiendas\n(Backend Central)" as modulo

cliente --> app : 1: Ingresa código Tracking QR
app --> modulo : 2: GET /api/encomiendas/{id}
modulo --> app : 3: Retorna Estado (Ej: "EN RUTA" - JSON)
app --> cliente : 4: Muestra ubicación actual en pantalla

@enduml